### ISSUE TITLE
Remove opting out of Ivy

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise-ng-quickstart#18]
Currently in .tsconfig, for the angularCompilerOptions, we are opting out from Ivy, i.e. ` "enableIvy": false`. I've tried and I haven't had any issues with Ivy and ids-enterprise-ng > 8.0, so I suggest the removal of this property (since it is true by default since Angular 9), or set it to true.

**Comment by tmcconechy** [comment]
Thanks, i changed it to true for now. https://github.com/infor-design/enterprise-ng-quickstart/commit/9a09e4c2da95561cc3b371d4b0ed9367a7e97051

Note i also disabled strict - will turn this on when https://github.com/infor-design/enterprise-ng/issues/755 is complete
